# Generated by Django 3.0.8 on 2020-08-29 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medic',
            fields=[
                ('name', models.TextField(primary_key=True, serialize=False)),
                ('profession', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('identifier', models.TextField(primary_key=True, serialize=False)),
                ('explanation', models.TextField()),
                ('medic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='umfrage.Medic')),
            ],
        ),
        migrations.CreateModel(
            name='Umfrage',
            fields=[
                ('key', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('is_completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UmfrageStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('umfrage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='umfrage.Umfrage')),
            ],
        ),
        migrations.CreateModel(
            name='UmfrageExplanation',
            fields=[
                ('umfragestep_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='umfrage.UmfrageStep')),
                ('text', models.TextField()),
            ],
            bases=('umfrage.umfragestep',),
        ),
        migrations.CreateModel(
            name='UmfrageRating',
            fields=[
                ('umfragestep_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='umfrage.UmfrageStep')),
                ('text', models.TextField()),
                ('min_value', models.PositiveIntegerField(default=1)),
                ('min_value_hint', models.TextField()),
                ('max_value', models.PositiveIntegerField(default=5)),
                ('max_value_hint', models.TextField()),
                ('value', models.PositiveIntegerField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
            ],
            bases=('umfrage.umfragestep',),
        ),
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField()),
                ('task', models.TextField()),
                ('message', models.TextField()),
                ('priority', models.TextField()),
                ('start_line', models.TextField(blank=True, null=True)),
                ('end_line', models.TextField(blank=True, null=True)),
                ('start_column', models.TextField(blank=True, null=True)),
                ('end_column', models.TextField(blank=True, null=True)),
                ('file_contents', models.TextField()),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='umfrage.Rule')),
            ],
        ),
        migrations.AddField(
            model_name='umfrage',
            name='violation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='umfrage.Violation'),
        ),
        migrations.CreateModel(
            name='UmfrageViolation',
            fields=[
                ('umfragestep_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='umfrage.UmfrageStep')),
                ('text', models.TextField()),
                ('violation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='umfrage.Violation')),
            ],
            bases=('umfrage.umfragestep',),
        ),
    ]
