# Generated by Django 3.0.8 on 2020-08-28 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medic',
            fields=[
                ('name', models.TextField(primary_key=True, serialize=False)),
                ('profession', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('identifier', models.TextField(primary_key=True, serialize=False)),
                ('explanation', models.TextField()),
                ('medic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='umfrage.Medic')),
            ],
        ),
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField()),
                ('task', models.TextField()),
                ('message', models.TextField()),
                ('priority', models.TextField()),
                ('start_line', models.TextField(blank=True, null=True)),
                ('end_line', models.TextField(blank=True, null=True)),
                ('start_column', models.TextField(blank=True, null=True)),
                ('end_column', models.TextField(blank=True, null=True)),
                ('file_contents', models.TextField()),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='umfrage.Rule')),
            ],
        ),
    ]
