# Generated by Django 3.0.8 on 2020-08-28 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umfrage', '0002_umfrage_umfrageexplanation_umfragerating_umfragestep_umfrageviolation'),
    ]

    operations = [
        migrations.AddField(
            model_name='umfrage',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
